export const PRODUCTS = [
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    },
    {
        image: '/shop/one.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Maxi Skirt, Exclusively at Macy's",
        regularPrice: 110.0,
        vipPrice: 33.49,
        vipOffer: 10.0,
        discount: 70,
        rating: 4,
        reviews: 1,
        colors: ['#FF0000', '#000000', '#FFFFFF']
    },
    {
        image: '/shop/four.webp',
        brand: 'I.N.C. International Concepts',
        name: "NEW! Women's Printed Tie-Waist Button-Front Maxi Dress, Exclusively at Macy's",
        regularPrice: 120.0,
        vipPrice: 35.99,
        vipOffer: 12.0,
        discount: 65,
        rating: 5,
        reviews: 2,
        colors: ['#000000', '#0000FF']
    }
    // Add more products as needed
];
